### ISSUE TITLE
FATAL EXCEPTION: AsyncTask #2

### ISSUE THREAD

**Issue by snsekar** [wkh237/react-native-fetch-blob#206]
Hi,
I am using RNFetchBlob.fs.lstat(path) api and getting following error in Android 4.2.2 

```
E/AndroidRuntime(31827): FATAL EXCEPTION: AsyncTask #2
E/AndroidRuntime(31827): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(31827): 	at android.os.AsyncTask$3.done(AsyncTask.java:299)
E/AndroidRuntime(31827): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
E/AndroidRuntime(31827): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
E/AndroidRuntime(31827): 	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
E/AndroidRuntime(31827): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
E/AndroidRuntime(31827): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
E/AndroidRuntime(31827): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
E/AndroidRuntime(31827): 	at java.lang.Thread.run(Thread.java:856)
E/AndroidRuntime(31827): Caused by: java.lang.NullPointerException
E/AndroidRuntime(31827): 	at com.RNFetchBlob.RNFetchBlobFS$1.doInBackground(RNFetchBlobFS.java:582)
E/AndroidRuntime(31827): 	at com.RNFetchBlob.RNFetchBlobFS$1.doInBackground(RNFetchBlobFS.java:571)
E/AndroidRuntime(31827): 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
E/AndroidRuntime(31827): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
E/AndroidRuntime(31827): 	... 4 more
```

Please help me to resolve issue

**Comment by wkh237** [comment]
@snsekar , thanks for reporting this issue.

I think that's because you passed `null` or `undefined` to the method and the native part didn't handle the exception well, as such the app crashed. I'll fix this issue in next releae 😄

**Comment by snsekar** [comment]
@wkh237 Thanks for fixing
