### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by cbjs** [wkh237/react-native-fetch-blob#571]
react-native: 0.49.3
react-native-fetch-blob: 0.10.8
os: android

same with https://github.com/wkh237/react-native-fetch-blob/pull/557

logcat output:

10-24 00:09:02.942 6724 7168 I am_crash: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File java.io.File.getParentFile()' on a null object reference, stack:
CRASH
10-24 00:09:02.942 6724 7168 I am_crash: com.RNFetchBlob.RNFetchBlobFS.getSystemfolders@216
CRASH
10-24 00:09:02.942 6724 7168 I am_crash: com.RNFetchBlob.RNFetchBlob.getConstants@84
CRASH
10-24 00:09:02.942 6724 7168 I am_crash: com.facebook.react.bridge.JavaModuleWrapper.getConstants@140
CRASH
10-24 00:09:02.942 6724 7168 I am_crash: android.os.Handler.handleCallback@815
CRASH
10-24 00:09:02.942 6724 7168 I am_crash: android.os.Handler.dispatchMessage@104
CRASH
10-24 00:09:02.942 6724 7168 I am_crash: com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage@31

**Comment by mehdijjz** [comment]
+1

**Comment by agrass** [comment]
Hi! Did anyone solve this?  @cbjs 

I'm with this issue:

```
Fatal Exception: java.lang.NullPointerException
       at java.io.File.fixSlashes(File.java:185)
       at java.io.File.<init>(File.java:134)
       at com.RNFetchBlob.RNFetchBlobFS.exists(RNFetchBlobFS.java:506)
       at com.RNFetchBlob.RNFetchBlob.exists(RNFetchBlob.java:159)
       at java.lang.reflect.Method.invokeNative(Method.java)
```

**Comment by pampang** [comment]
+1

**Comment by mehdijjz** [comment]
+1

**Comment by chrusart** [comment]
PR https://github.com/wkh237/react-native-fetch-blob/pull/619

**Comment by hwangjr** [comment]
+1

**Comment by ohmnakisa** [comment]
+1

**Comment by iMohammadReza** [comment]
+1
