### ISSUE TITLE
com.facebook.jni.CppException:Failed to create String from JSON

### ISSUE THREAD

**Issue by pampang** [wkh237/react-native-fetch-blob#572]
I've encounter this error when I used react-native-chched-image in ANDROID:
```
java.lang.RuntimeException:Error invoking callback 263
com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
......
Caused by:
com.facebook.jni.CppException:Failed to create String from JSON:
com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
android.os.Handler.handleCallback(Handler.java:739)
android.os.Handler.dispatchMessage(Handler.java:95)
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
android.os.Looper.loop(Looper.java:148)
com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
java.lang.Thread.run(Thread.java:818)
```

**Comment by AggarwalAnkit** [comment]
I am also getting same crash log. Don't know where it is crashing as I got it in Bugsnag crash report

**Comment by ifiokjr** [comment]
I get this when calling the `.json()` method on the response object.

On iOS everything seems fine. It even runs okay in an Android emulator, but when debugging on a device I get the following crash.

```
12-05 11:21:17.251 17871-19306/com.bgmobilenga E/unknown:ReactNative: Exception in native call
                                                                      java.lang.RuntimeException: Error invoking callback 14632
                                                                          at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                          at android.os.Handler.handleCallback(Handler.java:789)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                          at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                          at android.os.Looper.loop(Looper.java:164)
                                                                          at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                                          at java.lang.Thread.run(Thread.java:764)
                                                                       Caused by: com.facebook.jni.CppException: Failed to create Value from JSON: 
                                                                          at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                          at android.os.Handler.handleCallback(Handler.java:789) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                          at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                          at android.os.Looper.loop(Looper.java:164) 
                                                                          at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194) 
                                                                          at java.lang.Thread.run(Thread.java:764) 
``` 

The API endpoint either returns a PDF or JSON describing the issue, hence the reason for checking. 

Anyone found a workaround solution.

**Comment by zolaahihi** [comment]
Hello,

Any update on this issue?

**Comment by abtuhin** [comment]
Fatal Exception: java.lang.RuntimeException: Error invoking callback 9139
       at com.facebook.react.bridge.queue.NativeRunnable.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source)
       at android.os.Looper.loop(Looper.java:194)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(Unknown Source)
       at java.lang.Thread.run(Thread.java:818)



Caused by com.facebook.jni.CppException: Failed to create Value from JSON: 
       at com.facebook.react.bridge.queue.NativeRunnable.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source)
       at android.os.Looper.loop(Looper.java:194)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(Unknown Source)
       at java.lang.Thread.run(Thread.java:818)
